Ct passthrough filter
uml-robotics/robot-common-3d pull request #11
Opened 2024-08-15 19:02 UTC by Tags01

# Changes Made
## passthrough_filter_service:
- Introduced class format, moved main functionality to the constructor, and marked data private.
- Added missing header files.
- Added error checking for all input parameters: all parameters must produce a volumn with a
  positive, non-zero, non-NaN size. Node will shutdown on error. This was moved to its own
  function.
- Convert `fromROSMsg` -> `moveFromROSMsg`.
- Preserve TF frame information in the result.
- replace explicit `std::shared_ptr(new TYPE) ` with definition with `std::make_shared<TYPE>()` format.
- Convert parameter namespace to `std::string_view` to follow google style guidelines.

## simple_test_passthrough_filter:
 - Omit explicit test checks. This script is harder to test accurately since its very sensitive to input data. However, it's easy to verify the code works visually which is included in the script. These tests will be replaced anyways with dedicated unit tests so these can be omitted for now.

## Misc
- `CMakeLists.txt`: Added notes about why the program must not use `-Ofast` or `-ffast-math`
- `CMakeLists.txt`: Added the new files so they can be built
- Added two new launch files. These are mostly the same as with other commits. The default parameters for the bounding box in passthrough_filter default to a `1x1x1 m` cube centered at `(0, 0, 0)` 

# Evidence of Working Code
The darker background is the entire field of view of the camera, while the bright color segments only contain the filtered points. The default settings are used.
![ezgif-7-fc5fa396ea](https://github.com/user-attachments/assets/e4a3cabe-484f-4bb2-95f0-a48301307064)
When the arrow is moved up, it falls within the bound of the bottom of the bounding box so the colors appear brighter on the image.

2024-08-16 20:43 UTC, GregoryLeMasurier requested changes
Awesome! One small thing to clean up

2024-08-16 20:43 UTC, GregoryLeMasurier commented on pcl_utility_msgs/srv/PCLPassthroughFilter.srv
This is the same as the voxel grid service message - it helps make it easier to read this way (and it's the same way it was done before) but I wonder if we can reduce duplicated messages some way. Let's talk about this with the group next week

2024-08-16 20:43 UTC, GregoryLeMasurier commented on pcl_utilities/src/passthrough_filter_service.cpp
> +    // pass_x.setFilterLimitsNegative(false);
Do we need the commented out line?

2024-08-19 17:04 UTC, Tags01 commented
# Changes
- Added explicit dependencies for `rcl_interfaces`/`rclcpp`. These dependencies were missed because they are always included transitively. Dependencies in the CMakeLists.txt/package.xml are now alphabetical.
- Added explicit overflow checks when converting from double to float. This also resolves warnings in Clang with `-Wimplicit-float-conversions`
- Added comments to the launch script
- Changed out lvalue parameter to rvalue parameter in the test. Beforehand I used `std::move` on an lvalue parameter.

2024-08-20 13:54 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_passthrough_filter.cpp
> +  void process_point_cloud(PointCloud2 && point_cloud)
Why did we change to pass in an address of an address? Is this best practice? It seems to add overhead where we have to use std::move before each call, where it was handled for the user before

2024-08-20 13:54 UTC, GregoryLeMasurier commented on pcl_utilities/src/passthrough_filter_service.cpp
> +  double x_min_;
Why did we switch from float to double and then add in a bunch of checks to make sure the conversion happened correctly? Why can't we just use floats?

2024-08-20 14:50 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_passthrough_filter.cpp
> +  void process_point_cloud(PointCloud2 && point_cloud)
Addressed in person

2024-08-20 16:05 UTC, GregoryLeMasurier approved these changes

2024-08-20 20:30 UTC, GregoryLeMasurier requested changes
Forgot to check includes - small cleanup

2024-08-20 20:30 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_passthrough_filter.cpp
> +#include <cstddef>  // size_t
Not used in file

2024-08-20 20:30 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_passthrough_filter.cpp
> +#include <cstdint>  // int64_t
Not used in this file

2024-08-20 20:30 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_passthrough_filter.cpp
> +#include <functional>  // std::bind, std::placeholders
Not used in this file

2024-08-20 20:30 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_passthrough_filter.cpp
> +#include <ios>  // std::fixed, std::setprecision
Not used in this file

2024-08-20 20:30 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_passthrough_filter.cpp
> +#include <sstream>  // std::stringstream
Not used in this file

2024-08-20 20:45 UTC, GregoryLeMasurier approved these changes

2024-08-21 14:15 UTC, flynnbm approved these changes
Modifications to the original and overall format looks great

2024-08-21 14:16 UTC, merged