Ct port transform_point_cloud function
uml-robotics/robot-common-3d pull request #14
Opened 2024-08-19 18:19 UTC by Tags01

# Changes
## transform_point_cloud_service:
- Inlined the function `getFrameTransform`
- Converted camel to snake case.
- Rmmoved test/debugging print statements
- Added parameter for the max number of runs
## simple_test_transform_point_cloud:
- Publish a custom TF frame and transform.
- Set a source frame from the launch file
- Call the service and publish the result.
- No tests were added since this testing strategy will be changed later.
## CMakeLists.txt/Package.xml
- Add missing dependencies

# Working Code
... Pending

2024-08-20 20:37 UTC, GregoryLeMasurier requested changes
Only small documentation / include clean up - looks great!

2024-08-20 20:37 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_transform_point_cloud.cpp
> + * Description: A node to test the concatenate_point_cloud_service.
Update "concatenate_point_cloud_service"

2024-08-20 20:37 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_transform_point_cloud.cpp
> + * This node listens a point cloud message, then transforms the frame of the
Small grammar - "listens to a "

2024-08-20 20:37 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_transform_point_cloud.cpp
> +#include <cstdint>  // int64_t
Not used in this file

2024-08-20 20:37 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_transform_point_cloud.cpp
> +#include <functional>  // std::bind, std::placeholders
not used in this file

2024-08-20 20:37 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_transform_point_cloud.cpp
> +#include <ios>  // std::fixed, std::setprecision
Not used in this file

2024-08-20 20:37 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_transform_point_cloud.cpp
> +#include <optional>  // std::optional
Not used in this file

2024-08-20 20:37 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_transform_point_cloud.cpp
> +#include <random>
Not used in this file

2024-08-20 20:37 UTC, GregoryLeMasurier commented on pcl_utilities/src/transform_point_cloud_service.cpp
> +#include <sstream>  // std::stringstream
Not used in this file

2024-08-20 20:37 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_transform_point_cloud.cpp
> +#include <sstream>  // std::stringstream
Not used in this file

2024-08-20 20:37 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_transform_point_cloud.cpp
> +#include "rclcpp/subscription.hpp"
Not used in this file

2024-08-20 20:37 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_transform_point_cloud.cpp
> +#include "tf2_ros/buffer.h"
Is this used?

2024-08-20 20:37 UTC, GregoryLeMasurier commented on pcl_utilities/src/transform_point_cloud_service.cpp
> +#include <cstdint>  // std::int64_t
Not used in this file

2024-08-20 20:37 UTC, GregoryLeMasurier commented on pcl_utilities/src/transform_point_cloud_service.cpp
> +#include <iomanip>  // std::quoted
Not used in this file

2024-08-20 20:37 UTC, GregoryLeMasurier commented on pcl_utilities/src/transform_point_cloud_service.cpp
> +#include <string>
Not used in this file

2024-08-20 20:45 UTC, Tags01 commented on pcl_utilities/src/transform_point_cloud_service.cpp
> +#include <cstdint>  // std::int64_t
comment should not have `std::` prefix

2024-09-05 20:18 UTC, GregoryLeMasurier approved these changes

2024-09-05 20:18 UTC, GregoryLeMasurier commented
Looks good to me

2025-01-08 16:25 UTC, flynnbm commented
There are several conflicting lines involving dependency and executable targets in the CMakeLists.txt file that need to be resolved before I can approve the merge; I'm going to close this request so you can resolve the conflict before resubmitting

2025-01-08 21:01 UTC, merged