Ct Concatenate Point Cloud
uml-robotics/robot-common-3d pull request #6
Opened 2024-08-05 00:34 UTC by Tags01

# Ported Concatenate Point Cloud script to ROS2
## Changes to concatenate_point_cloud.cpp:
- Changed naming from "pointcloud" -> "point_cloud" to conform with the ROS2 naming.
- Restrict max size of input point clouds to 400 to make sure the point cloud VLA will fit on the stack.
- Use explicit case from point_cloud.size() (type size_t) to unsigned int to avoid narrowing-conversion warnings.
- Assert that only one TF frame is provided for all messages and put the same frame in the output of the message.
- Add documentation including explicitly mentioning which fields of PointCloud2 are and are not managed by PCL
- Explicitly include dependencies for PCL.

## Additions in simple_test_concatenate_point_cloud
- Create a queue of N successive camera messages and send them to the service. One the service compiles, publish the result to a topic. 
- Assertion that the size of the output point cloud is greater than or equal to the largest input point cloud.

## Changes to CMakeLists:
- Add PCL as an explicit dependency
- Add documentation for identifying and handling issues finding PCL on certain environments.

## Stylistic changes from the last commit
- Pass the callback via rvalue instead of lvalue to signal that create_client/create_service should take ownership of the function. The old code works because RCLCPP copies the callback within the implementation but this subject to change.
- use std:: prefix on types from "cstdint". The ROS2 style guide (derived from Google) recommends not using the "std" prefix but omitting the prefix reduces portability of the code.

## Output of Simple Test
![simple_test_concatenated_point_clouds](https://github.com/user-attachments/assets/8ee512fb-bbfa-4dcc-9cd2-3688b852f577)

2024-08-05 20:56 UTC, GregoryLeMasurier requested changes
Great initial port - I like the checks you've added to ensure the input clouds are being concatenated appropriately. Added a few questions (which we can discuss tomorrow with the group) and minor clean up

This PR will be blocked until #9 is resolved

2024-08-05 20:56 UTC, GregoryLeMasurier commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +#include <pcl_conversions/pcl_conversions.h>  // std::shared_ptr
Don't need to specify what we use from ROS / PCL, this is mostly to make sure we only are using includes that are necessary - which is mostly needed for the non-standard includes.

2024-08-05 20:56 UTC, GregoryLeMasurier commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +#include <memory>
// std::make_shared

2024-08-05 20:56 UTC, GregoryLeMasurier commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +#include <pcl/impl/point_types.hpp>  // pcl::PointXYZRGB
PCL - don't need comment

2024-08-05 20:56 UTC, GregoryLeMasurier commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +#include <rclcpp/logging.hpp>  // rclcpp::Logger
ROS - don't need comment

2024-08-05 20:56 UTC, GregoryLeMasurier commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +
Can we clean up the include orders - in your tests you grouped the generic stuff first - then ROS - then maybe we put PCL after - then custom includes?

2024-08-05 20:56 UTC, GregoryLeMasurier commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +constexpr size_t MAX_POINT_CLOUDS = 400U;
400 isn't guaranteed to prevent stack overflow. This would depend on the size of the point clouds. That being said - I don't think we will ever overflow the stack or use 400 point clouds so this is probably fine if we decide to keep it. I'm wondering if this this check is necessary since the value was arbitrarily determined and it was not in our original file.

2024-08-05 20:56 UTC, GregoryLeMasurier commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +  if (cloud_list_size > MAX_POINT_CLOUDS) {
As mentioned above - is this really a valid check?

2024-08-05 20:56 UTC, GregoryLeMasurier commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +      RCLCPP_ERROR_STREAM(node_logger,
If we fail here - does the service still return success?

2024-08-05 20:56 UTC, GregoryLeMasurier commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +  (void)dummy_subscriber;
Why do we cast the service to void?

2024-08-05 20:56 UTC, GregoryLeMasurier commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +      "concatenate_point_cloud", std::move(callback));
std::move wasn't used in your voxel grid PR. Which is the correct method? If this is best practice then lets create another PR to update the voxel grid service.

2024-08-05 20:56 UTC, GregoryLeMasurier commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +  auto node = std::make_shared<rclcpp::Node>("concatenate_point_cloud_service");
While the original files are set up in this manner, I don't think we should keep it set up differently than the voxel grid service. The voxel grid service wrapped everything in a class which was derived from rclcpp::Node, which seems to be best practice for ROS2

2024-08-05 20:56 UTC, GregoryLeMasurier commented on pcl_utilities/tests/simple_test_concatenate_point_cloud.cpp
> +#include <cstdint>  // size_t
You mentioned needing to fix something about this

2024-08-05 20:56 UTC, GregoryLeMasurier commented on pcl_utilities/tests/simple_test_concatenate_point_cloud.cpp
> +#include <climits>
What do we use from this?

2024-08-05 20:56 UTC, GregoryLeMasurier commented on pcl_utilities/tests/simple_test_concatenate_point_cloud.cpp
> +#include <ios>  // std::fixed, std::set_percision
typo on: ``std::setprecision``

2024-08-05 20:56 UTC, GregoryLeMasurier commented on pcl_utilities/tests/simple_test_concatenate_point_cloud.cpp
> +#include <memory>  // std::shared_ptr, std::make_shared
``std::shared_ptr`` not used

2024-08-05 20:56 UTC, GregoryLeMasurier commented on pcl_utilities/tests/simple_test_concatenate_point_cloud.cpp
> +#include <sensor_msgs/msg/point_cloud2.hpp>
Message should move to the ROS section of your include list

2024-08-05 20:56 UTC, GregoryLeMasurier commented on pcl_utilities/tests/simple_test_concatenate_point_cloud.cpp
> +    rclcpp::Client<PCLConcatenatePointCloud>::SharedPtr concatenate_point_cloud_filter_client_;
This isn't a filter, I would just remove that small part of the name

2024-08-05 22:52 UTC, Tags01 commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +  (void)dummy_subscriber;
dummy_subscriber is unused, casting to void indicates that that the compiler should not produce a warning with `-Wunused`

2024-08-05 22:54 UTC, Tags01 commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +      "concatenate_point_cloud", std::move(callback));
`std::move` or pass directly by rvalue is the best method. It indicates that create_service should take ownership of the callback and it’s lifetime should be valid for the entire lifetime of the service

2024-08-05 22:56 UTC, Tags01 commented on pcl_utilities/tests/simple_test_concatenate_point_cloud.cpp
> +#include <cstdint>  // size_t
size_t is in cstdef, so cstdint is unused

2024-08-06 14:31 UTC, Tags01 commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +constexpr size_t MAX_POINT_CLOUDS = 400U;
I'll update the comment above, the limit should almost never be reached but should still be effective in the short term. The lowest stack size for mainstream 64bit OS's seems to be 512kb (MacOS). If someone were to pass the max number of point clouds only about 10% of available stack usage. Long term this should probably be migrated to use heap memory to reduce the memory constraints.

2024-08-06 14:32 UTC, Tags01 commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +  if (cloud_list_size > MAX_POINT_CLOUDS) {
I'm believe so, let me know what you think

2024-08-06 14:32 UTC, Tags01 commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +      RCLCPP_ERROR_STREAM(node_logger,
Yes it does, ill fix that

2024-08-06 14:34 UTC, Tags01 commented on pcl_utilities/tests/simple_test_concatenate_point_cloud.cpp
> +#include <climits>
`INT_MAX`, ill add a comment

2024-08-07 18:44 UTC, Tags01 commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +constexpr size_t MAX_POINT_CLOUDS = 400U;
The VLA and size checks were removed in favor of merging the loops

2024-08-07 18:47 UTC, Tags01 commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +  (void)dummy_subscriber;
fixed with transition to class

2024-08-07 19:35 UTC, Tags01 commented on pcl_utilities/tests/simple_test_concatenate_point_cloud.cpp
> +#include <climits>
`cstdint` is now used with `cstdef`. Comments are added.

2024-08-08 01:05 UTC, Tags01 commented
# Updates to the Ported Code
## General Updates
- Applied all of Greg's suggested changes.
- Updated all includes and include comments. Note that the `pcl_utility_msg` related headers are treated as project specific and are put at the bottom of the list.
- Improved C++ Style Guide Conformance.
- Added `output="screen"` to launch files to see more output.
- removed `-Wno-vla` flag.

## Stylistic changes to concatenated_point_cloud
- Moved the implementation into a class. Moved the contents of the main function into the constructor. This also removes the cast to `void.`

## Performance Related Changes
- Merge the conversion and concatenation for loops into one. This implicitly removes the need on an internal point cloud array and the size check. 
- Remove the point cloud array and the size check. This reduces the memory footprint and simplifies the code structure. This has no effect on program behavior.
- Change `fromROSMsg` to `moveFromROSMsg` This transfers ownership of the underlying point cloud buffer to PCL instead of using a deep copy. This removes the need to copy all the points in the point cloud. This does have the effect of invalidating the `cloud_list_in` vector within the request, but this has no outward side-effects.

## Potential Further Changes/Alternative Routes
- Keep an internal point cloud array could be kept and use `std::reduce` with a parallel executor, `std::execution::par_unseq`. Performing an operation like the following could speed up the program by running the concatenation operations parallel between threads. This option would need profiling.
```
std::transform<std::execution::par_unseq>(
    req->cloud_array.begin(), req->cloud_array.end(), std::plus<>());
```
- The executor could be made multithreaded. This will require accessing whether the intended use case for this code would would attempt to call the service concurrently. Additional considerations such as the QoS cache size are required.

## Changes to simple_test_concatenate_point cloud
The original code was problematic in that relied on calling a service from a subscriber callback. This led to an issue where the QoS of the service would fill, and additional requests would never return. Transitioning a new program format simplifies the logic. Dedicated testing logic will replace the test function. 
- Replace the camera callback with a `rclcpp::wait_for_message`. This would ensure the service would finish before another request was sent.
- Replace `rclcpp::spin` with `rclcpp::spin_until_future_complete`. Both cannot be used concurrently.
- Add max timeout on waiting for messages and service results. This will alert the user that the service never responded and continue to the next task preventing freezing.
- Isolate testing, callback, and spin logic into separate functions.
- Fix the bug where the script would not stop immediately `CRTL-C`

## Evidence of Working Code
![working_concat_point_cloud](https://github.com/user-attachments/assets/941e0015-b90d-47d1-8c33-20344cee0a3b)

## Many of these changes should be back-ported to `voxel_grid_filter`

2024-08-14 16:49 UTC, GregoryLeMasurier requested changes
Great! Only small linting changes. Ignored style issues with voxel grid - we'll fix that in a different PR. 

Lets also try to run with the linter too https://docs.ros.org/en/galactic/The-ROS2-Project/Contributing/Developer-Guide.html#linters-and-static-analysis

2024-08-14 16:49 UTC, GregoryLeMasurier commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +      PCLConcatenatePointCloud::Response::SharedPtr res) {
Small style thing - brace should not cuddle on function: https://docs.ros.org/en/humble/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#open-versus-cuddled-braces

2024-08-14 16:49 UTC, GregoryLeMasurier commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +      {
Brace should cuddle on if: https://docs.ros.org/en/humble/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#open-versus-cuddled-braces

2024-08-14 16:49 UTC, GregoryLeMasurier commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +      {
Brace should cuddle on if: https://docs.ros.org/en/humble/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#open-versus-cuddled-braces

2024-08-14 16:49 UTC, GregoryLeMasurier commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +int main(int argc, char ** argv) {
Brace should not cuddle on function: https://docs.ros.org/en/humble/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#open-versus-cuddled-braces

2024-08-14 16:49 UTC, GregoryLeMasurier commented on pcl_utilities/src/concatenate_point_cloud_service.cpp
> +class ConcatenatePointCloudService: public rclcpp::Node {
Brace should not cuddle on class: https://docs.ros.org/en/humble/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#open-versus-cuddled-braces

2024-08-14 16:49 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_concatenate_point_cloud.cpp
> +    {
Brace should cuddle on while: https://docs.ros.org/en/humble/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#open-versus-cuddled-braces

2024-08-14 16:49 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_concatenate_point_cloud.cpp
> +      {
Brace should cuddle on if: https://docs.ros.org/en/humble/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#open-versus-cuddled-braces

2024-08-14 16:49 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_concatenate_point_cloud.cpp
> +  void process_point_cloud(PointCloud2& point_cloud) {
Brace should not cuddle on function: https://docs.ros.org/en/humble/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#open-versus-cuddled-braces

2024-08-14 16:49 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_concatenate_point_cloud.cpp
> +    {
Brace should cuddle on if: https://docs.ros.org/en/humble/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#open-versus-cuddled-braces

2024-08-14 16:49 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_concatenate_point_cloud.cpp
> +    {
Brace should cuddle on else: https://docs.ros.org/en/humble/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#open-versus-cuddled-braces

2024-08-14 16:49 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_concatenate_point_cloud.cpp
> +    {
Brace should cuddle on if: https://docs.ros.org/en/humble/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#open-versus-cuddled-braces

2024-08-14 16:49 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_concatenate_point_cloud.cpp
> +    {
This should not be split on two lines.

Once it is on one line, brace should cuddle on if: https://docs.ros.org/en/humble/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#open-versus-cuddled-braces

2024-08-14 16:49 UTC, GregoryLeMasurier commented on pcl_utilities/src/tests/simple_test_concatenate_point_cloud.cpp
> +int main(int argc, char ** argv) {
Brace should not cuddle on function: https://docs.ros.org/en/humble/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#open-versus-cuddled-braces

2024-08-14 19:23 UTC, Tags01 commented
# Changes
- All of Greg's comments resolved
- Replaced all `RCLCPP_ERROR` with `RCLCPP_ERROR_STREAM` for consistency (also fixes Wformat-security warnings in Clang)
- Linter shows no issues for these files.

2024-08-14 21:24 UTC, GregoryLeMasurier approved these changes
Looks good to me

2024-08-15 13:31 UTC, flynnbm approved these changes
It all looks good to me, I see some of the edits you brought up in our last meeting. I assume you've run your tests since I saw the test output in the README.

2024-08-15 13:42 UTC, merged